import time
time.sleep(0.1) 

from machine import Pin, PWM

# Sensors
IR_yellowsensor = Pin(2, Pin.IN, Pin.PULL_UP)
IR_Dangersensor = Pin(3, Pin.IN, Pin.PULL_UP)

# LED
green_led = Pin(9, Pin.OUT)
yellow_led = Pin(10, Pin.OUT)
red_led = Pin(11, Pin.OUT)

zone = "SAFE" # Default mode 
object_in_zone = False

# Buzzer *LLM USAGE*. The Buzzer logic part is generated by LLM #
buzzer = PWM(Pin(5))
buzzer.freq(1000)
buzzer.duty_u16(0)


# Timing duration of zones 
starttime_dangerzone = None 
danger_duration = 0

starttime_yellowzone = None 
zone_duration = 0

# State of sensors 

previousyellow_state = 1  # 1 = beam is clear 0 = beam is broken !
previousDanger_state = 1  

# Which direction person is moving towards : "DANGER" or "YELLOW "
direction = None 



while True:

    # Reading sensor states 
    current_danger = IR_Dangersensor.value()
    current_yellow = IR_yellowsensor.value()

    # Check if beam is broken

    if previousyellow_state == 1 and current_yellow == 0:
        print("Yellow sensor crossed !")

    if previousDanger_state == 1 and current_danger == 0:
        print("Danger sensor crossed!")

    
    if current_danger == 0:  #
        object_in_zone = True 
        zone = "DANGER" # Danger must have highest priority.
        buzzer.duty_u16(30000) # Buzzer activates

        if starttime_dangerzone is None:
            starttime_dangerzone = time.ticks_ms()
            print("IMMEDIATE DANGER") 

        green_led.value(0)
        red_led.value(1)
        yellow_led.value(0)


    elif current_yellow == 0:
        object_in_zone = True
        zone = "YELLOW"    # 2nd priority but still High risk zone
        buzzer.duty_u16(0) 
       
        if starttime_yellowzone is None:
            starttime_yellowzone = time.ticks_ms() 
            print("High risk ")

        green_led.value(0)
        yellow_led.value(1) # Only this led will be on
        red_led.value(0)

    else:
        
        object_in_zone = False
        zone = "SAFE"
        buzzer.duty_u16(0)

        green_led.value(1)
        yellow_led.value(0)
        red_led.value(0)


    if starttime_dangerzone is not None and zone != "DANGER":
        danger_duration = time.ticks_diff(
            time.ticks_ms(),
            starttime_dangerzone
        )

        danger_duration = danger_duration / 1000

        print(
            "Amount of time in danger zone",
            danger_duration, "seconds")
    
        starttime_dangerzone = None


    if starttime_yellowzone is not None and zone != "YELLOW":
        zone_duration = time.ticks_diff(
            time.ticks_ms(),
            starttime_yellowzone 
        )

        zone_duration = zone_duration / 1000

        print("Amount of time in yellow zone",
               zone_duration, "seconds")

        starttime_yellowzone = None 


    # Saving sensor values for next loop
    previousyellow_state = current_yellow
    previousDanger_state = current_danger

    time.sleep(0.1)