apiVersion: 1

datasources:
  - name: InfraredFox TimescaleDB
    uid: infrafox-timescaledb
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: sensor
    secureJsonData:
      password: alessandro
    jsonData:
      database: infrafox
      sslmode: disable
      postgresVersion: 1800
      timescaledb: true
      